version : '3.0'

services :
 my_db :
      image : mysql
      command : mysqld --default-authentication-plugin=mysql_native_password
      restart : always
      networks :
       - overlay
      environment :
        MYSQL_ROOT_PASSWORD : "123456"
      volumes:
       - "/docker/mysql/data:/var/lib/mysql"
      ports:
       - "3306:3306"
      depends_on :
       - my_nginx 
 
 my_php_fpm :
     image : php:v0.3
     restart : always 
     ports :
      - "9000:9000"
     volumes :
      - "/data/www:/var/www/html"
     networks :
      - overlay

 my_nginx : 
    image : nginx:v2.0
    restart : always
    ports : 
     - "80:80"
    networks :
     - overlay
    environment:
     php: my_php_fpm
    volumes : 
     - "/data/www:/usr/share/nginx/html"

networks :
   overlay:
