FROM nginx:latest
COPY nginx.conf /etc/nginx/nginx.conf
RUN set -x \
 && sed -i s@/archive.ubuntu.com/@/mirrors.163.com/@g /etc/apt/sources.list \
 && apt-get clean \
 && apt-get update \
 && apt-get install iputils-ping -y
